// <auto-generated />
using HamburgerProje.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamburgerProje.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HamburgerProje.Data.Ekstra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ekstralar");
                });

            modelBuilder.Entity("HamburgerProje.Data.EkstraMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EkstraId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EkstraId");

                    b.HasIndex("MenuId");

                    b.ToTable("EkstraMenuler");
                });

            modelBuilder.Entity("HamburgerProje.Data.EkstraSiparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EkstraId")
                        .HasColumnType("int");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EkstraId");

                    b.HasIndex("SiparisId");

                    b.ToTable("EkstraSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Hamburger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hamburgerler");
                });

            modelBuilder.Entity("HamburgerProje.Data.HamburgerMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HamburgerId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HamburgerId");

                    b.HasIndex("MenuId");

                    b.ToTable("HamburgerMenuler");
                });

            modelBuilder.Entity("HamburgerProje.Data.HamburgerSiparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HamburgerId")
                        .HasColumnType("int");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HamburgerId");

                    b.HasIndex("SiparisId");

                    b.ToTable("HamburgerSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Icecek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Icecekler");
                });

            modelBuilder.Entity("HamburgerProje.Data.IcecekMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IcecekId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IcecekId");

                    b.HasIndex("MenuId");

                    b.ToTable("IcecekMenuler");
                });

            modelBuilder.Entity("HamburgerProje.Data.IcecekSiparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IcecekId")
                        .HasColumnType("int");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IcecekId");

                    b.HasIndex("SiparisId");

                    b.ToTable("IcecekSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menuler");
                });

            modelBuilder.Entity("HamburgerProje.Data.MenuSiparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("SiparisId");

                    b.ToTable("MenuSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("bit");

                    b.Property<double>("Toplam")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Sos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Soslar");
                });

            modelBuilder.Entity("HamburgerProje.Data.SosMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("SosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("SosId");

                    b.ToTable("SosMenuler");
                });

            modelBuilder.Entity("HamburgerProje.Data.SosSiparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<int>("SosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("SosId");

                    b.ToTable("SosSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.EkstraMenu", b =>
                {
                    b.HasOne("HamburgerProje.Data.Ekstra", "Ekstra")
                        .WithMany("EkstraMenuler")
                        .HasForeignKey("EkstraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Menu", "Menu")
                        .WithMany("EkstraMenuler")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekstra");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("HamburgerProje.Data.EkstraSiparis", b =>
                {
                    b.HasOne("HamburgerProje.Data.Ekstra", "Ekstra")
                        .WithMany("EkstraSiparisler")
                        .HasForeignKey("EkstraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Siparis", "Siparis")
                        .WithMany("EkstraSiparisler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekstra");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("HamburgerProje.Data.HamburgerMenu", b =>
                {
                    b.HasOne("HamburgerProje.Data.Hamburger", "Hamburger")
                        .WithMany("HamburgerMenuler")
                        .HasForeignKey("HamburgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Menu", "Menu")
                        .WithMany("HamburgerMenuler")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hamburger");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("HamburgerProje.Data.HamburgerSiparis", b =>
                {
                    b.HasOne("HamburgerProje.Data.Hamburger", "Hamburger")
                        .WithMany("HamburgerSiparisler")
                        .HasForeignKey("HamburgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Siparis", "Siparis")
                        .WithMany("HamburgerSiparisler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hamburger");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("HamburgerProje.Data.IcecekMenu", b =>
                {
                    b.HasOne("HamburgerProje.Data.Icecek", "Icecek")
                        .WithMany("IcecekMenuler")
                        .HasForeignKey("IcecekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Menu", "Menu")
                        .WithMany("IcecekMenuler")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icecek");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("HamburgerProje.Data.IcecekSiparis", b =>
                {
                    b.HasOne("HamburgerProje.Data.Icecek", "Icecek")
                        .WithMany("IcecekSiparisler")
                        .HasForeignKey("IcecekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Siparis", "Siparis")
                        .WithMany("IcecekSiparisler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icecek");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("HamburgerProje.Data.MenuSiparis", b =>
                {
                    b.HasOne("HamburgerProje.Data.Menu", "Menu")
                        .WithMany("MenuSiparisler")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Siparis", "Siparis")
                        .WithMany("MenuSiparisler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("HamburgerProje.Data.SosMenu", b =>
                {
                    b.HasOne("HamburgerProje.Data.Menu", "Menu")
                        .WithMany("SosMenuler")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Sos", "Sos")
                        .WithMany("SosMenuler")
                        .HasForeignKey("SosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Sos");
                });

            modelBuilder.Entity("HamburgerProje.Data.SosSiparis", b =>
                {
                    b.HasOne("HamburgerProje.Data.Siparis", "Siparis")
                        .WithMany("SosSiparisler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProje.Data.Sos", "Sos")
                        .WithMany("SosSiparisler")
                        .HasForeignKey("SosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Sos");
                });

            modelBuilder.Entity("HamburgerProje.Data.Ekstra", b =>
                {
                    b.Navigation("EkstraMenuler");

                    b.Navigation("EkstraSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Hamburger", b =>
                {
                    b.Navigation("HamburgerMenuler");

                    b.Navigation("HamburgerSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Icecek", b =>
                {
                    b.Navigation("IcecekMenuler");

                    b.Navigation("IcecekSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Menu", b =>
                {
                    b.Navigation("EkstraMenuler");

                    b.Navigation("HamburgerMenuler");

                    b.Navigation("IcecekMenuler");

                    b.Navigation("MenuSiparisler");

                    b.Navigation("SosMenuler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Siparis", b =>
                {
                    b.Navigation("EkstraSiparisler");

                    b.Navigation("HamburgerSiparisler");

                    b.Navigation("IcecekSiparisler");

                    b.Navigation("MenuSiparisler");

                    b.Navigation("SosSiparisler");
                });

            modelBuilder.Entity("HamburgerProje.Data.Sos", b =>
                {
                    b.Navigation("SosMenuler");

                    b.Navigation("SosSiparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
